import type { ApprovedDataSource } from "@/types/data-sources";

const APPROVED_DATA_SOURCES: ApprovedDataSource[] = [
  {
    id: "sec-company-tickers",
    name: "SEC Company Tickers",
    category: "classification",
    mode: "api",
    policy: "fair_access_required",
    currentUse: true,
    url: "https://www.sec.gov/file/company-tickers",
    note: "Offizielle Referenzliste für Ticker/CIK. Automatisierung ist erlaubt, aber nur mit Fair-Access-Headern und moderater Rate.",
  },
  {
    id: "sec-sic-list",
    name: "SEC SIC Codes",
    category: "classification",
    mode: "reference",
    policy: "fair_access_required",
    currentUse: false,
    url: "https://www.sec.gov/search-filings/standard-industrial-classification-sic-code-list",
    note: "Offizielle Branchenklassifikation. Sinnvoll als zusätzliche Referenz für spätere Gruppierungs- und Branchen-Mappings.",
  },
  {
    id: "stooq-csv",
    name: "Stooq CSV",
    category: "market_data",
    mode: "csv",
    policy: "best_effort",
    currentUse: true,
    url: "https://stooq.com/",
    note: "Nützlicher Gratis-Fallback für Tageshistorien. Geeignet für Kursreihen und Markt-Kontext, nicht als institutioneller Primärfeed.",
  },
  {
    id: "openbb",
    name: "OpenBB",
    category: "market_data",
    mode: "wrapper",
    policy: "api_allowed",
    currentUse: true,
    url: "https://www.openbb.co/",
    note: "Wrapper-Layer für mehrere freie Datenquellen. Gut als Fallback- und Enrichment-Schicht.",
  },
  {
    id: "fmp-sector-industry",
    name: "Financial Modeling Prep",
    category: "market_data",
    mode: "api",
    policy: "api_allowed",
    currentUse: false,
    url: "https://site.financialmodelingprep.com/developer/docs/stable/sector-performance-snapshot",
    note: "Beste nächste API für echte Sektor- und Industrie-Snapshots inklusive Company Screener. Sinnvoll für Market Heat, sobald ein API-Key hinterlegt ist.",
  },
  {
    id: "polygon-snapshots",
    name: "Polygon Snapshots",
    category: "market_data",
    mode: "api",
    policy: "api_allowed",
    currentUse: false,
    url: "https://polygon.io/docs/rest/stocks/snapshots/top-market-movers",
    note: "Geeignet für Movers und breite Snapshot-Daten. Je nach Plan 15 Minuten verzögert oder real-time; daher sauber als Delayed/Live markieren.",
  },
  {
    id: "marketaux-news",
    name: "Marketaux News & Sentiment",
    category: "reference",
    mode: "api",
    policy: "api_allowed",
    currentUse: false,
    url: "https://www.marketaux.com/documentation",
    note: "Nützlich für Themen-Hitze über News, Entitäten, Branchen und Sentiment. Gute Ergänzung zu Preis-/Volumen-Heat, wenn ein API-Key vorhanden ist.",
  },
  {
    id: "fred-api",
    name: "FRED API",
    category: "macro",
    mode: "api",
    policy: "api_allowed",
    currentUse: false,
    url: "https://fred.stlouisfed.org/docs/api/fred/",
    note: "Offizielle und kostenlose Makro-API der St. Louis Fed. Stark für Regime-, Zins- und Konjunktur-Kontext.",
  },
  {
    id: "yahoo-unofficial",
    name: "Yahoo Finance",
    category: "market_data",
    mode: "wrapper",
    policy: "best_effort",
    currentUse: true,
    url: "https://finance.yahoo.com/",
    note: "Praktisch für Gratis-MVPs, aber inoffiziell und rate-limit-anfällig. Deshalb nur mit Cache und Fallbacks.",
  },
  {
    id: "finviz-reference",
    name: "Finviz",
    category: "reference",
    mode: "reference",
    policy: "best_effort",
    currentUse: true,
    url: "https://finviz.com/groups.ashx",
    note: "Gute Referenz für Gruppen- und Heat-Ansichten. Nicht als aggressive zentrale Scraping-Quelle ausbauen.",
  },
  {
    id: "tradingview-reference",
    name: "TradingView Sector & Industry",
    category: "reference",
    mode: "reference",
    policy: "manual_only",
    currentUse: false,
    url: "https://www.tradingview.com/markets/stocks-usa/sectorandindustry-sector/",
    note: "Gut zum visuellen Abgleich. Wegen Terms und Display-Orientierung nur als manuelle Referenz, nicht als Produktions-Scraper.",
  },
  {
    id: "barchart-reference",
    name: "Barchart Industry Rankings",
    category: "reference",
    mode: "reference",
    policy: "manual_only",
    currentUse: false,
    url: "https://www.barchart.com/stocks/sectors/industry-rankings",
    note: "Inhaltlich nützlich zum Gegencheck. Nicht automatisiert scrapen, weil die Terms Daten-Mining und Robots untersagen.",
  },
];

export function getApprovedDataSources(): ApprovedDataSource[] {
  return APPROVED_DATA_SOURCES;
}
